# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VirtualAssistGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/robotic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"font-weight:bold;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton#button{\n"
"font-size:15px;\n"
"border-radius: 15px;\n"
"background:#2d89ef;\n"
"}\n"
"\n"
"QPushButton#button:hover{\n"
"font-size:15px;\n"
"border-radius: 15px;\n"
"background:#2b5797;\n"
"}\n"
"\n"
"QWidget{\n"
"background-image: url(:/images/images/backgroud.jpg);\n"
"}\n"
"\n"
"QFrame#contenedor{\n"
"background:#1d1d1d;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QLabel#title{\n"
"font-size:24px;\n"
"background:#1d1d1d;\n"
"}\n"
"\n"
"QLabel#robot{\n"
"background:#1d1d1d;\n"
"}\n"
"\n"
"QScrollArea{\n"
"background:#1d1d1d;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"border-radius:0px;\n"
"background:#1d1d1d;\n"
"}\n"
"")
        self.principal = QtWidgets.QWidget(MainWindow)
        self.principal.setStyleSheet("")
        self.principal.setObjectName("principal")
        self.contenedor = QtWidgets.QFrame(self.principal)
        self.contenedor.setGeometry(QtCore.QRect(20, 20, 321, 481))
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.title = QtWidgets.QLabel(self.contenedor)
        self.title.setGeometry(QtCore.QRect(20, 10, 281, 41))
        self.title.setAutoFillBackground(False)
        self.title.setObjectName("title")
        self.robot = QtWidgets.QLabel(self.contenedor)
        self.robot.setGeometry(QtCore.QRect(100, 50, 121, 151))
        self.robot.setText("")
        self.robot.setPixmap(QtGui.QPixmap(":/images/images/robot.png"))
        self.robot.setObjectName("robot")
        self.scrollArea = QtWidgets.QScrollArea(self.contenedor)
        self.scrollArea.setGeometry(QtCore.QRect(10, 200, 301, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll = QtWidgets.QWidget()
        self.scroll.setGeometry(QtCore.QRect(0, 0, 301, 211))
        self.scroll.setObjectName("scroll")
        self.text = QtWidgets.QTextEdit(self.scroll)
        self.text.setEnabled(True)
        self.text.setGeometry(QtCore.QRect(0, 0, 301, 211))
        self.text.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text.setObjectName("text")
        self.scrollArea.setWidget(self.scroll)
        self.button = QtWidgets.QPushButton(self.contenedor)
        self.button.setGeometry(QtCore.QRect(20, 430, 281, 23))
        self.button.setAutoFillBackground(False)
        self.button.setStyleSheet("")
        self.button.setObjectName("button")
        self.robot.raise_()
        self.title.raise_()
        self.scrollArea.raise_()
        self.button.raise_()
        MainWindow.setCentralWidget(self.principal)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Virtual Assist"))
        self.title.setText(_translate("MainWindow", "A SIMPLE VIRTUAL ASSIST"))
        self.text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'century gothic\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.button.setText(_translate("MainWindow", "INICIAR"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
